os: osx
osx_image: xcode10.1  
language: objective-c
xcode_project: CiTestFramework.xcodeproj
xcode_scheme: CiTestFramework
xcode_destination: platform=iOS Simulator,name=iPhone X,OS=12.1

before_script:
- date

