os: osx
osx_image: xcode10.1  
language: objective-c
xcode_project: CiTestFramework.xcodeproj
xcode_scheme: CiTestFramework
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone XS

before_install:
- instruments -s devices